---
- hosts: all
  become: true

  tasks:
  - name: Import Key
    apt_key:
      url:  http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
      state: present

  - name: Repositories for ruby, git, virtualbox
    apt_repository:
      repo: "{{item}}"
    with_items:
    - ppa:brightbox/ruby-ng
    - ppa:git-core/ppa
    - deb http://download.virtualbox.org/virtualbox/debian trusty contrib

  - name: Install vagrant
    apt:
      deb: "{{item}}"
    with_items:
      - https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb

  - name: Install Base Packages
    apt:
      cache_valid_time: 3600
      update_cache: yes
      state: present
      name: "{{item}}"
    with_items:
    - ruby2.3
    - ruby2.3-dev
    - git
    - vim
    - htop
    - virtualbox

  - name: Setup git/gem for user vagrant
    copy:
      src: "{{item}}"
      dest: /home/vagrant/.{{item}}
      owner: vagrant
      group: vagrant
      mode: u=rw,g=rw,o=r
    with_items:
    - gitconfig
    - gemrc

  - name: Setup Path for gem
    lineinfile:
      dest: /home/vagrant/.bashrc
      line: export PATH=/home/vagrant/.gem/ruby/2.3.0/bin:$PATH
      state: present

  - name: Install Serverspec
    become_user: vagrant
    gem:
      name: "{{item}}"
      state: latest
      user_install: yes
    with_items:
      - rake
      - serverspec
      - serverspec-runner
      - test-kitchen
      - kitchen-vagrant
